# Generated by Django 4.1 on 2022-09-02 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epic_events', '0002_alter_customer_date_updated_event_contract'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='groups',
            new_name='role',
        ),
    ]
