# Generated by Django 4.1 on 2022-09-02 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epic_events', '0003_rename_groups_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='username',
            field=models.CharField(default=0.0101010101010101, max_length=60),
            preserve_default=False,
        ),
    ]
