# Generated by Django 4.1 on 2022-09-02 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epic_events', '0004_customer_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='username',
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
