# Generated by Django 4.1 on 2022-09-05 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epic_events', '0006_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
