# Generated by Django 4.1 on 2022-09-13 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epic_events', '0009_rename_status_contract_is_signed_customer_is_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Management', 'Management'), ('Sale', 'Sale'), ('Support', 'Support')], max_length=25),
        ),
    ]
