# Generated by Django 4.1 on 2022-10-05 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epic_events', '0015_alter_user_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Manager', 'Manager'), ('Vendeur', 'Vendeur'), ('Support', 'Support')], max_length=25),
        ),
    ]
